version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=devices
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '5431:5432'
    volumes:
      - pg:/var/lib/postgresql/data

volumes:
  pg:
    name: pg
